import java.sql.*;
import javax.swing.*;
import java.awt.HeadlessException;
import static java.lang.Math.abs;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
//import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muhammad Shaheer
 */
public class Books_Return extends javax.swing.JFrame {
    MyConnection dbc=new MyConnection();
    Connection conn=dbc.connectme();
    ResultSet rs,rs1;
    PreparedStatement pstmt,pstmt1;
    /**
     * Creates new form Return
     */
    public Books_Return() {
        super("RETURN BOOK");
        initComponents();        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        returnid = new javax.swing.JTextField();
        bookid = new javax.swing.JTextField();
        teacherid = new javax.swing.JTextField();
        studentid = new javax.swing.JTextField();
        DateChooserissue = new com.toedter.calendar.JDateChooser();
        DateChooserreturn = new com.toedter.calendar.JDateChooser();
        btnshow = new javax.swing.JButton();
        btnreturn = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnpay = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true), "RETURN BOOK", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 20), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RETURN ID");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BOOK ID");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TEACHER ID");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("STUDENT ID");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ISSUE DATE");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RETURN DATE");

        returnid.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        returnid.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        bookid.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        bookid.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        teacherid.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        teacherid.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        studentid.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        studentid.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        DateChooserissue.setDateFormatString("MMM dd, yyyy");
        DateChooserissue.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        DateChooserreturn.setDateFormatString("MMM dd, yyyy");
        DateChooserreturn.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        btnshow.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnshow.setText("SEARCH");
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });

        btnreturn.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnreturn.setText("RETURN BOOK");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnclear.setText("CLEAR ALL FIELDS");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnback.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnback.setText("GO BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnpay.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnpay.setText("PAYMENT");
        btnpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returnid)
                            .addComponent(bookid)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)
                        .addComponent(teacherid))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addComponent(studentid))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addComponent(DateChooserissue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnshow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(btnreturn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnclear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnpay))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DateChooserreturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(returnid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bookid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(teacherid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(DateChooserissue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(DateChooserreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnshow)
                    .addComponent(btnreturn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnclear)
                    .addComponent(btnpay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnback)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        int qaty = 0;
        try
        {
            java.util.Date returndate1 = DateChooserreturn.getDate();
                        
            String aa;
            java.util.Date date =new java.util.Date();
            DateFormat df=new SimpleDateFormat("MMM dd, yyyy");
            aa=df.format(date);
            java.util.Date returndate2 = new SimpleDateFormat("MMM dd, yyyy").parse(aa);
            
            int datediff;
            datediff=(int) ((returndate1.getTime()-returndate2.getTime())/(1000*60*60*24));
            System.out.println(returndate1);
            System.out.println(returndate2);
            System.out.println(datediff);
            if(datediff>=0)
            {
                pstmt1 = conn.prepareStatement("select quantity from books where book_id=?");
                pstmt1.setString(1,bookid.getText());
                rs1=pstmt1.executeQuery();
                if(rs1.next())
                {
                    qaty=Integer.parseInt(rs1.getString("quantity"));
                    rs1.close();
                    pstmt1.close();
                }            
                pstmt1 = conn.prepareStatement("update books set quantity=? where book_id=?");
                pstmt1.setString(1,Integer.toString(qaty+1));
                pstmt1.setString(2,bookid.getText());
                pstmt1.execute();
                pstmt=conn.prepareStatement("delete from issue_return_books where issue_return_id=?");
                pstmt.setString(1, returnid.getText());
                pstmt.execute();
                JOptionPane.showMessageDialog(null,"Book returned successfully!!!!");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Book returned unsuccessfully!!!!\nYou have to pay "+abs(datediff)+"/- Rs");
            }           
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        } 
        catch (ParseException ex) 
        {
            Logger.getLogger(Books_Return.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnreturnActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        setVisible(false);
        Home_Page ob=new Home_Page();
        ob.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        returnid.setText("");
        bookid.setText("");
        teacherid.setText("");
        studentid.setText("");
        bookid.requestFocus();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
        try
        {
            pstmt=conn.prepareStatement("select * from issue_return_books where issue_return_id=?");
            pstmt.setString(1,returnid.getText());
            rs=pstmt.executeQuery();
            if(rs.next())
            {
                String add1=rs.getString("book_id");
                bookid.setText(add1);
                String add2=rs.getString("teacher_id");
                teacherid.setText(add2);
                String add3=rs.getString("student_id");
                studentid.setText(add3);
                String add4 = rs.getString("issue_date");
                java.util.Date issuedate = new SimpleDateFormat("MMM dd, yyyy").parse(add4);
                DateChooserissue.setDate(issuedate);
                String add5 = rs.getString("return_date");
                java.util.Date returndate = new SimpleDateFormat("MMM dd, yyyy").parse(add5);
                DateChooserreturn.setDate(returndate);
                rs.close();
                pstmt.close();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"No book issued!!!!","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        } 
        catch (ParseException ex) 
        {
            Logger.getLogger(Books_Return.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btnshowActionPerformed

    private void btnpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpayActionPerformed
        JOptionPane.showMessageDialog(null,"Payment Successfully!!!!");
        int qaty = 0;
        try
        {
            pstmt1 = conn.prepareStatement("select quantity from books where book_id=?");
            pstmt1.setString(1,bookid.getText());
            rs1=pstmt1.executeQuery();
            if(rs1.next())
            {
                qaty=Integer.parseInt(rs1.getString("quantity"));
                rs1.close();
                pstmt1.close();
            }            
            pstmt1 = conn.prepareStatement("update books set quantity=? where book_id=?");
            pstmt1.setString(1,Integer.toString(qaty+1));
            pstmt1.setString(2,bookid.getText());
            pstmt1.execute();
            pstmt=conn.prepareStatement("delete from issue_return_books where issue_return_id=?");
            pstmt.setString(1, returnid.getText());
            pstmt.execute();
            JOptionPane.showMessageDialog(null,"Book returned successfully!!!!");
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        } 
        
    }//GEN-LAST:event_btnpayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books_Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books_Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books_Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books_Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Books_Return().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooserissue;
    private com.toedter.calendar.JDateChooser DateChooserreturn;
    private javax.swing.JTextField bookid;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnpay;
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton btnshow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField returnid;
    private javax.swing.JTextField studentid;
    private javax.swing.JTextField teacherid;
    // End of variables declaration//GEN-END:variables
}
