/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class Home_Page extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Home_Page() {
        super("HOME PAGE");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnaddbook = new javax.swing.JButton();
        btnaddstud = new javax.swing.JButton();
        btnaddteacher = new javax.swing.JButton();
        btnissue = new javax.swing.JButton();
        btnreturn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        filemenu = new javax.swing.JMenu();
        logoutmenuitem = new javax.swing.JMenuItem();
        exitmenuitem = new javax.swing.JMenuItem();
        editmenu = new javax.swing.JMenu();
        deletemenuitem = new javax.swing.JMenuItem();
        modifymenuitem = new javax.swing.JMenuItem();
        viewmenu = new javax.swing.JMenu();
        regstudmenuitem = new javax.swing.JMenuItem();
        regteachermenuitem = new javax.swing.JMenuItem();
        allbooksmenuitem = new javax.swing.JMenuItem();
        btnissuebooks = new javax.swing.JMenuItem();
        aboutmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnaddbook.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnaddbook.setText("ADD NEW BOOK");
        btnaddbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddbookActionPerformed(evt);
            }
        });

        btnaddstud.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnaddstud.setText("ADD NEW STUDENT");
        btnaddstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddstudActionPerformed(evt);
            }
        });

        btnaddteacher.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnaddteacher.setText("ADD NEW TEACHER");
        btnaddteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddteacherActionPerformed(evt);
            }
        });

        btnissue.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnissue.setText("ISSUE BOOK");
        btnissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissueActionPerformed(evt);
            }
        });

        btnreturn.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnreturn.setText("RETURN BOOK");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });

        filemenu.setText("FILE");

        logoutmenuitem.setText("LOGOUT");
        logoutmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutmenuitemActionPerformed(evt);
            }
        });
        filemenu.add(logoutmenuitem);

        exitmenuitem.setText("EXIT");
        exitmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitmenuitemActionPerformed(evt);
            }
        });
        filemenu.add(exitmenuitem);

        jMenuBar1.add(filemenu);

        editmenu.setText("EDIT");

        deletemenuitem.setText("DELETE");
        deletemenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletemenuitemActionPerformed(evt);
            }
        });
        editmenu.add(deletemenuitem);

        modifymenuitem.setText("MODIFY");
        modifymenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifymenuitemActionPerformed(evt);
            }
        });
        editmenu.add(modifymenuitem);

        jMenuBar1.add(editmenu);

        viewmenu.setText("VIEW");

        regstudmenuitem.setText("REGESTERED STUDENTS");
        regstudmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regstudmenuitemActionPerformed(evt);
            }
        });
        viewmenu.add(regstudmenuitem);

        regteachermenuitem.setText("REGESTERED TEACHERS");
        regteachermenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regteachermenuitemActionPerformed(evt);
            }
        });
        viewmenu.add(regteachermenuitem);

        allbooksmenuitem.setText("ALL BOOKS");
        allbooksmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allbooksmenuitemActionPerformed(evt);
            }
        });
        viewmenu.add(allbooksmenuitem);

        btnissuebooks.setText("ISSUED BOOKS");
        btnissuebooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissuebooksActionPerformed(evt);
            }
        });
        viewmenu.add(btnissuebooks);

        jMenuBar1.add(viewmenu);

        aboutmenu.setText("ABOUT");
        aboutmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutmenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(aboutmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnissue)
                .addGap(18, 18, 18)
                .addComponent(btnreturn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnaddbook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnaddstud)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btnaddteacher)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddbook)
                    .addComponent(btnaddstud))
                .addGap(18, 18, 18)
                .addComponent(btnaddteacher)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnissue)
                    .addComponent(btnreturn))
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddbookActionPerformed
        setVisible(false);
        New_Book ob = new New_Book();
        ob.setVisible(true);
    }//GEN-LAST:event_btnaddbookActionPerformed

    private void btnaddstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddstudActionPerformed
        setVisible(false);
        New_Student ob=new New_Student();
        ob.setVisible(true);
    }//GEN-LAST:event_btnaddstudActionPerformed

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        setVisible(false);
        Books_Return ob=new Books_Return();
        ob.setVisible(true);
    }//GEN-LAST:event_btnreturnActionPerformed

    private void btnissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissueActionPerformed
        setVisible(false);
        Books_Issue ob=new Books_Issue();
        ob.setVisible(true);
    }//GEN-LAST:event_btnissueActionPerformed

    private void logoutmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutmenuitemActionPerformed
        setVisible(false);
        Login_Menu ob=new Login_Menu();
        ob.setVisible(true);
    }//GEN-LAST:event_logoutmenuitemActionPerformed

    private void exitmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitmenuitemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitmenuitemActionPerformed

    private void regstudmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regstudmenuitemActionPerformed
        setVisible(false);
        Show_Students ob=new Show_Students();
        ob.setVisible(true);
    }//GEN-LAST:event_regstudmenuitemActionPerformed

    private void allbooksmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allbooksmenuitemActionPerformed
        setVisible(false);
        Show_Books ob=new Show_Books();
        ob.setVisible(true);
    }//GEN-LAST:event_allbooksmenuitemActionPerformed

    private void aboutmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutmenuMouseClicked
        setVisible(false);
        About ob=new About();
        ob.setVisible(true);
    }//GEN-LAST:event_aboutmenuMouseClicked

    private void deletemenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletemenuitemActionPerformed
        setVisible(false);
        Records_Delete ob=new Records_Delete();
        ob.setVisible(true);
    }//GEN-LAST:event_deletemenuitemActionPerformed

    private void modifymenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifymenuitemActionPerformed
        setVisible(false);
        Records_Modify ob=new Records_Modify();
        ob.setVisible(true);
    }//GEN-LAST:event_modifymenuitemActionPerformed

    private void btnaddteacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddteacherActionPerformed
        setVisible(false);
        New_Teacher ob=new New_Teacher();
        ob.setVisible(true);
    }//GEN-LAST:event_btnaddteacherActionPerformed

    private void regteachermenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regteachermenuitemActionPerformed
        setVisible(false);
        Show_Teachers ob=new Show_Teachers();
        ob.setVisible(true);
    }//GEN-LAST:event_regteachermenuitemActionPerformed

    private void btnissuebooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissuebooksActionPerformed
        setVisible(false);
        Show_Issued_Books ob=new Show_Issued_Books();
        ob.setVisible(true);
    }//GEN-LAST:event_btnissuebooksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutmenu;
    private javax.swing.JMenuItem allbooksmenuitem;
    private javax.swing.JButton btnaddbook;
    private javax.swing.JButton btnaddstud;
    private javax.swing.JButton btnaddteacher;
    private javax.swing.JButton btnissue;
    private javax.swing.JMenuItem btnissuebooks;
    private javax.swing.JButton btnreturn;
    private javax.swing.JMenuItem deletemenuitem;
    private javax.swing.JMenu editmenu;
    private javax.swing.JMenuItem exitmenuitem;
    private javax.swing.JMenu filemenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem logoutmenuitem;
    private javax.swing.JMenuItem modifymenuitem;
    private javax.swing.JMenuItem regstudmenuitem;
    private javax.swing.JMenuItem regteachermenuitem;
    private javax.swing.JMenu viewmenu;
    // End of variables declaration//GEN-END:variables
}
